# Generated by Django 2.2 on 2020-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='catalog_items',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='tags', to='api.Catalog'),
        ),
    ]
