# Generated by Django 2.2 on 2020-07-28 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200728_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('Removed User'), to=settings.AUTH_USER_MODEL),
        ),
    ]
