# Generated by Django 2.2 on 2020-09-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200921_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='catalog_items',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='api.Catalog'),
        ),
    ]
