# Generated by Django 2.2 on 2020-07-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200728_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='items',
            new_name='catalog_items',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('file', models.FileField(default=None, upload_to='media/%Y/%m/%d/')),
                ('catalog_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Catalog')),
            ],
        ),
    ]
