# Generated by Django 2.2 on 2020-07-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200728_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='file',
        ),
    ]
