# Generated by Django 2.2 on 2020-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200728_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('flag', models.ImageField(upload_to='media/flags/')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default=None, on_delete=models.SET('DELETED'), to='api.Countries'),
        ),
    ]
