# Generated by Django 2.2 on 2020-07-29 14:54

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200729_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.FileField(upload_to='media/flags/', validators=[api.validators.validate_svg]),
        ),
    ]
