# Generated by Django 2.2 on 2020-07-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200729_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='name',
            new_name='countryname',
        ),
    ]
