# Generated by Django 2.2 on 2020-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200807_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('DELETED'), to='api.Countries'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/users/'),
        ),
    ]
