# Generated by Django 2.2 on 2020-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200807_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
